Added Hyprland service This is a massive commit. My Guix system is now capable of generating a Lua config for the Hyprland window manager. There's still many features that are missing, but it has all of the essentials.

diff --git a/scripts/run-with-hypr-env b/scripts/run-with-hypr-env
--- a/scripts/run-with-hypr-env
+++ b/scripts/run-with-hypr-env
@@ -19,39 +19,32 @@
 # This script runs a provided command, ensuring it has access to environment variables set by Hyprland.
 # This is useful for things like Shepherd services, which are ran within a sandboxed environment.
 
-# TODO: When Hyprland can be configured from Guix, ensure it creates the signature file as expected.
+# TODO: Find a working way to get the ID of the user running Hyprland.
 
-sig_file="${XDG_RUNTIME_DIR:-/tmp}/hyprland_sig"
-max_file_checks=30
+# HACK: Yes, hardcoding the UID here is extremely stupid.
+# For some reason, the UID environment variable doesn't work for home Shepherd services.
+# This is basically a band-aid fix that should be replaced soon.
 
-if [[ -z "$1" ]]; then
-    echo "Error: Program not specified"
+hypr_dir="/run/user/1000/hypr"
+
+if [ ! -d "$hypr_dir" ]; then
+    echo "Error: Failed to find Hyprland socket directory" >&2
     exit 1
 fi
 
-if ! pgrep -x Hyprland > /dev/null; then
-    echo "Error: No Hyprland process found"
+# This tries to find the last-modified Hyprland socket.
+socket=$(find "$hypr_dir" -maxdepth 1 -type d -printf '%T@ %f\n' 2>/dev/null \
+    | tail -n +2 \
+    | sort -rn \
+    | head -1 \
+    | cut -d ' ' -f 2-)
+
+if [ -z "$socket" ]; then
+    echo "Error: Hyprland socket directory is empty" >&2
     exit 2
 fi
 
-# If the Hyprland signature file doesn't exist yet, wait until it does.
-# This loop can time out if the file isn't created in time, causing the script to exit.
-check_count=1
-while [[ ! -f "$sig_file" ]]; do
-    if [[ $check_count -eq $max_file_checks ]]; then
-        echo "Error: Timed out waiting for the Hyprland signature file to be created"
-        exit 3
-    fi
-
-    sleep 1
-    echo "Waited for $check_count second\(s\) on the Hyprland signature file"
-    
-    ((check_count++))
-done
-
-# Get the instance signature of the current Hyprland instance.
-# When Hyprland starts, it should cache the signature in this file.
-export HYPRLAND_INSTANCE_SIGNATURE=$(cat "$sig_file")
+export HYPRLAND_INSTANCE_SIGNATURE="$socket"
 
 # Run the provided command with all arguments.
 # This replaces the current process.
